# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Run Powershell publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -name: Publish to Gallery
      run: ./PSActions/PSGalleryPublish.ps1
      shell: pwsh
